apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-gr4b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-gr4b
    app.kubernetes.io/part-of: devfile-sample-go-basic-1
  name: devfile-sample-go-basic-gr4b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-gr4b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-gr4b
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jiazhu-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-gr4b@sha256:98bf1746232259d2ac2d742e1c13d1bbf4f8b2a3e69815928376e91b8d52969a
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
