apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: managed-serviceaccount-bsmy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jiazhu-tenant/devfile-sample-go-basic-1/managed-serviceaccount-bsmy@sha256:be83e7bb317c0032036f220450366ecfa4fe7d2bbb4d78a75f0648eb4ed0c709
        name: container-image
        resources: {}
status: {}
