apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount-bsmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount-bsmy
    app.kubernetes.io/part-of: devfile-sample-go-basic-1
  name: managed-serviceaccount-bsmy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: managed-serviceaccount-bsmy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: managed-serviceaccount-bsmy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jiazhu-tenant/devfile-sample-go-basic-1/managed-serviceaccount-bsmy@sha256:be83e7bb317c0032036f220450366ecfa4fe7d2bbb4d78a75f0648eb4ed0c709
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
