apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount-bsmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount-bsmy
    app.kubernetes.io/part-of: devfile-sample-go-basic-1
  name: managed-serviceaccount-bsmy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: managed-serviceaccount-bsmy
status:
  loadBalancer: {}
